apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shreybatra/sample-frontend
        env:
        - name: BACKEND_URL
          value: "http://backend-svc:8000"
        ports:
        - containerPort: 5173
