frontend:
  image: shreybatra/sample-frontend
  replicas: 1
  port: 5173
  nodePort: 31000

backend:
  image: shreybatra/sample-backend
  replicas: 1
  port: 8000

redis:
  image: redis
  replicas: 1
  port: 6379
